---
engines:
  pmd:
    exclude_paths:
      - "src/**"

exclude_paths:
  - "**.md"
  - "**.css"
  - "**.css.map"
  - "**.scss"
  - "public/**"
  - "build/**"
  - "src/tests/**"
  - "src/seed/docs/**"
  - "src/seed/tests/**"
  - "node_modules/**"
  - "coverage/**"
  - ".git/**"