---
engines:
  pmd:
    exclude_paths:
      - "src/**"

exclude_paths:
  - "**.md"
  - "**.json"
  - "**.css"
  - "**.css.map"
  - "**.scss"
  - "coverage/**"
  - "build/**"
  - "docs/seed/**"
  - "public/**"
  - "src/tests/**"
  - "src/seed/tests/**"
  - "node_modules/**"
  - ".git/**"
  - ".github/**"
  - ".vscode/**"

  # - "bin/**"
  # - "src/seed/examples/**"
  # - "src/seed/gql/**"