### __Seed builder__
#   Autogenerated commands
#   Add custom commands at the end

FROM node:14.19.0-alpine
WORKDIR /
COPY package.json .
RUN apk update && apk add openssh-client
RUN npm install --silent
ENV PATH /node_modules/.bin:$PATH
WORKDIR /app
COPY . .

# __End autogenerated__
# Include commands after this block
###