### __Seed builder__
#   Autogenerated commands
#   Add custom commands at the end

FROM node:22.16.0
WORKDIR /
COPY package.json .

# __End autogenerated__
# Include commands after this block
###

RUN npm install --legacy-peer-deps
ENV PATH=/node_modules/.bin:$PATH
WORKDIR /app
COPY . .