version: 0.0
os: linux

files: 
  - source: /
    destination: /home/ubuntu/#APP_DIR#
    overwrite: true
    
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu