version: "3.7"

services:

  reactjs:
    build:
      context: ../../.
      dockerfile: Dockerfile
    command: /bin/sh -c "npm start"
    volumes:
      - ../../.:/app
      - /app/node_modules
    ports:
      - "${REACTJS_PORT}:${REACTJS_PORT}"

  codacy-cli:
    image: "codacy/codacy-analysis-cli"
    logging:
      driver: none