name: Deployment

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:

  test:
    uses: ./.github/workflows/test_wf.yml

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [test]

    steps:
      - name: Setup pem
        id: setup-pem
        env:
          PRIVATE_KEY: ${{ secrets.SERVER_PEM }}
          DEPLOY: ${{ secrets.ENABLE_DEPLOY }}
        if: env.DEPLOY == 'TRUE'
        run:
          echo "$PRIVATE_KEY" >> $HOME/key.pem && chmod 400 $HOME/key.pem

      - name: Update server
        env:
          DEPLOY: ${{ secrets.ENABLE_DEPLOY }}
        if: env.DEPLOY == 'TRUE'
        run:
          ssh -i $HOME/key.pem -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_NAME }} './deploy-web.sh ${{ secrets.GIT_PATH }}'